name: Deploy Website ke Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
    - name: Ambil kode dari GitHub
      uses: actions/checkout@v4

    - name: Upload via FTP ke hosting
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        server-dir: ./public_html/deploypengumuman/
